# Logistics

## Visas

Entry requirements in Japan vary by nationality. For complete information on visa requirements, visit Japan's [Ministry of Foreign Affairs](https://www.mofa.go.jp/j_info/visit/visa/). For exempt countries, including the United States and much of Europe, the standard visit allowed is 90 days.

## Arrival & departure

## Money
While most retailers in large cities accept credit cards, many small businesses and restaurants are cash only. ATMs are commonly available in convenience stores, and traveling with a no-fee debit card (e.g. Charles Schwab) makes getting cash easy. Some larger chains (like Lawson) have enabled tap to pay via preloaded cards, like the transit-oriented [Suica card](https://www.jreast.co.jp/multi/en/pass/suica.html).

## Eating

Options for dining and casual meals vary widely, depending mainly on the density of a location. It's possible to find a good burrito or Turkish food in Tokyo, but many small towns might have just one or two local restaurants (or none! -- in these cases, the humble convenience store is a saving grace). Japanese food like ramen, sushi, okonomiyaki, curry, etc are plentiful and good. For those with dietary restrictions, options can sometimes be difficult to find or discern. [HappyCow](https://www.happycow.net/) can sometimes offer guidance, but coverage outside of large metros is spotty. 

## Sleeping

## Bathing

Some campgrounds offer showers (free or pay), but the best option for bathing -- by far -- is the local onsen. They can be found in big cities and tiny towns, and often for just a few hundred yen offer an opportunity for shoewring, soaking in hot baths, and often saunas and cold plunges. Some provide soap, some sell it, and some are BYO (ditto towels). The best cycling days are those that end at an onsen. Each onsen will post rules to observe (no cell phones, wash before soaking, etc), which should be observed. Bonus bathing opportunities: some towns and rest areas provide free outdoor foot baths. 

## Transit

Getting around Japan while not riding your bike is quite doable -- extensive train systems, city and regional buses, and ferries can take you (and often your bike) to most places. Keep in mind that to bring your bike on trains, you'll need to pack it into a rinko bag and carry it on as luggage (this can also happen on ferries in rough weather). 

### Buses

Many mid-sized and large cities have extensive bus networks, which can get full at peak times. It's a good idea to carry exact change if you don't have the appropriate transit card. Pay when exiting the bus (fares are often distance-dependent). 

### Trains

Japan's [rail networks](https://www.jrpass.com/trains-in-japan) are rightly lauded: they are extensive, fast, and reliable (by US standards, anyway!). Depending on your route and timetable, you may want to buy tickets in advance. 

### Ferries

Ferries are an inevitability of island-hopping and are generally easy to navigate with bicycles. In most cases, you can buy a separate ticket for your bike and roll it on board the car deck, where ferry crew will secure it will you ride in the passenger area. Trailers may require an additional fee. Only the largest and busiest ferries require reservations in advance. In case of weather, like high winds, bicycles may be allowed on board only as rinko-ed luggage.

## Mechanicals

Cycling in Japan is popular, and so bike shops can be found in mid-sized towns around the country. That said, components for YOUR bike may be harder to come by. While it's easy to pay for very affordable tuneups and minor repairs as needed, pack your own tubes, spare derailleur hangers, extra chain, brake pads, patches, and other small parts. Have a reasonably complete tool kit in case of equipment failures on the road. 

## Budget
