# Quickstart

##  Highlights

* [Shimanami Kaido](#shimanami-kaido) -- Believe the hype. It's an
  island-hopping fly-over of an inland sea -- *but on a bike!* (**Easy**; 1 day
  minimum)

* [Yamanami Highway](#yamanami-highway) -- An amazing alpine ride that takes you
  coast-to-coast across the width of Kyushu, from Matsumoto to Beppu or Oita,
  via Aso National Park. (**Medium**; 2 days minimum)

* [Aomori highlands](#aomori-highlands) -- Lake Towada and Towada-Hachimantai
  National Park offer superb riding and camping as a quick stop on on a longer
  tour, or as part of a two-day loop starting and ending in Aormori city. Don't
  miss the short-but-splendid downhill run from the eastern shore of Lake Towada
  through Orase Gorge-*ous!* (**Medium**; 2 days minimum)

* Norikura Skyline -- 

* [Bandai-Azuma Skyline](#bandai-azuma-skyline) -- (**Difficult**; 1 day min)

* [The Nakasendo](#the-nakasendo) -- Completionists will get a huge kick out of
  pushing their bikes up steep, cobblestone horrorshows. The rest of us will
  enjoy varied riding along -- but only occasionally *on* -- Japan's most
  famouse Edo-era trade route from Tokyo to Kyoto. (**Mega**; 1 week minimum; 10
  days comfortable.)

* [Length of Japan](#length-of-japan) (LoJ) -- Start at Cape Sata on the
  southernmost tip of Kyushu and make your way to Cape Soya on the northermost
  tip of Hokkaido. Or vice versa. (**Mega**; 60 days minimum. FKT 33 days.)

## Top itineraries

* A day or two -- [Shimanami Kaido](#shimanami-kaido).

  From a logistical standpoint, it doesn't much matter which end of the route
  you choose to start at. This is such a popular objective that you'll be able
  to find transportation services for yourself and your bike without trying
  terribly hard. Buy yourself an early start and enjoy a truly amazing ride over
  man-made structures that will make you feeling like you're flying over the
  sea. The most stunning views are on the Imabari side.

* A week -- [The Nakasendo](#the-nakasendo).

  From Tokyo:

  From Kyoto:

* Two weeks -- [Tohoku](#tohoku)

  Starting from Shirakawa in the south or Aomori in the north, string together a
  long wandering ride between three big volcanic lakes: Inawashiro, Tozawa, and
  Towada. Highlights include the Bandai-Azuma Skyline and Towada-Hachimantai
  National Park. The direct route between the three is lakes is moutainous
  With two full weeks it's possible to squeeze in a few days on
  the Sanriku Fukko coast on the Pacific.

* 1 month -- 

  Summer: Circuit of Hokkaido.

  Summer, spring, or fall: North of Japan.

* 3 months -- [Length of Japan](#length-of-japan)

## Know before you go

* Riding the roads -- As with most Asian countries, bikes are a constant. School
  kids use them. Grannies use them. They're everywhere... *except actually
  riding in traffic!* Thankfully, Japanese drivers are very careful, respectful,
  and well-trained.

* Bike lanes -- These come and go, sometimes with no warning at all. It's almost
  a rule that any good bike lane in Japan won't last for more than a couple of
  miles.

* Bikes on public transit -- Generally speaking, a bicycle is *only* allowed on
  public transit if it is *completely covered* by a special bag called a "rinko
  bag." The only exception here is ferries, where bikes can be rolled right on
  right on and parked with the cars. Read more about this in the [Ferries](#ferries)
  section.

:::{.callout-warning title="Boxes are not 'rinko'"}

You should NOT expect to take boxed bikes on public transit. Exceptions exist
and are noted for cities where large boxes are acceptable trains or buses. Read
more about arrival and departure strategies in the
[Logistics](#arrival-departure) section.

:::

* Tunnels -- These are everywhere in Japan and take a bit of getting used to.
  Both traffic lanes will typically have a raised pedestrian walkway for
  emergency use, but bike lanes are seldom to be found. Furthermore, the
  walkways generally aren't wide enough to safely ride a loaded bike on. The
  default option with tunnels is to turn on your lights and ride in the traffic
  lane.

:::{.callout-important title="Sketchy tunnels"}

Some tunnels have been deemed dangerous or impassable to bicycles. These are
listed in the [Appendix](#sketchy-tunnels).

:::

* Bears, monkeys, and deer -- These animals can be real hazards; take warning
  signs seriously. If you ride long enough in Japan, you *might* see a bear, you
  will *probably* see a monkey, and you will *almost be killed* by a deer that jumps out
  into the road.

* Mountain weather --

* Language barrier -- Outside of folks in tourism, the Japanese don't speak much
  English. They do, however, mostly tolerate use of Google translate by foreigners.
