name: str(equals="main", ignore_case=False, required=True)
protected: enum(True, required=True)
protection: include('_protection', required=True)
---
_protection:
  enabled: enum(True, required=True)
  enforce_admins: enum(True, required=True)
  restrictions: null(required=False)
  required_status_checks: include('_rsc', required=True)
  required_pull_request_reviews: include('_rprr', required=True)
_rsc:
  strict: enum(True, required=True)
  contexts: list(max=0, required=True)
_rprr:
  dismiss_stale_reviews: enum(True, required=True)
  require_code_owner_reviews: enum(True, required=True)
  require_approving_review_count: enum(1, required=True)

  # required_status_checks:
  #   strict: true
  #   contexts:
  #     - ci/test

  # required_pull_request_reviews:
  #   dismiss_stale_reviews: true
  #   require_code_owner_reviews: true
  #   required_approving_review_count: 2
