private: bool(required=True, equals=False)
default_branch: str(required=True, equals="main", ignore_case=False)
has_issues: bool(required=True, equals=True)
has_wiki: bool(required=True, equals=False)
has_projects: bool(required=True, equals=False)
has_downloads: bool(required=True, equals=False)
has_pages: bool(required=True, equals=False)
has_discussions: bool(required=True, equals=False)
allow_forking: bool(required=True, equals=False)
