private: enum(False, required=True)
default_branch: str(equals="main", ignore_case=False, required=True)
has_issues: enum(True, required=True)
has_wiki: enum(False, required=True)
has_projects: enum(False, required=True)
has_downloads: enum(False, required=True)
has_pages: enum(False, required=True)
has_discussions: enum(False, required=True)
# allow_forking: enum(False, required=True)
