name: Check Repository Compliance

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  compliance-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo snap install dyff

      # - name: Fetch Branch Protection Rules
      #   run: |
      #     curl -s \
      #     -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
      #     -H "Accept: application/vnd.github+json" \
      #     https://api.github.com/repos/${{ github.repository }}/branches/main/protection > current_state.json

      - name: Fetch all branches
        env:
          PAGER:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
          --method GET \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/branches \
            > branches.json

      - name: Convert JSON to YAML
        run: |
          dyff yaml branches.json > branches.yml
          echo "Converted JSON to YAML:"
          cat branches.yml

      - name: Compare with Desired State
        run: |
          dyff between .github/repo/branch-settings.yml branches.yml
