name: Check Repository Compliance

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  compliance-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo snap install dyff
          pip install yamale

      - name: Fetch repo settings
        env:
          PAGER:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
          --method GET \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }} \
            > repo.json

      - name: Convert repo JSON to YAML
        run: |
          dyff yaml repo.json > repo.yml
          echo "Converted JSON to YAML:"
          cat repo.yml

      - name: Validate repo.yml vs schema
        run: |
          yamale \
          --schema .github/repo/repo-settings.yml \
          repo.yml

      - name: Fetch main branch settings
        env:
          PAGER:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
          --method GET \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/branches/main \
            > main.json

      - name: Convert main JSON to YAML
        run: |
          dyff yaml main.json > main.yml
          echo "Converted JSON to YAML:"
          cat main.yml

      - name: Validate main.yml vs schema
        run: |
          yamale \
          --schema .github/repo/branch-settings.yml \
          main.yml
